# Reference this view as prod__products
schema: PROD
table_name: PRODUCTS

dimensions:
  product_id:
    sql: '"PRODUCT_ID"'
    format: ID

  product_name:
    sql: '"PRODUCT_NAME"'

  product_type:
    sql: '"PRODUCT_TYPE"'

  product_description:
    sql: '"PRODUCT_DESCRIPTION"'

  product_price:
    sql: '"PRODUCT_PRICE"'

  is_food_item:
    sql: '"IS_FOOD_ITEM"'

  is_drink_item:
    sql: '"IS_DRINK_ITEM"'

measures:
  count:
    aggregate_type: count

#The info below was pulled from your dbt repository and is read-only.
dbt:
  name: products
  target_schema: PROD
  config:
    materialized: table
  code: |-
    with

    products as (

        select * from {{ ref('stg_products') }}

    )

    select * from products
